{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
stringData:
  userID: {{ .Values.secret.userID }}
  userKey: {{ .Values.secret.userKey }}
  {{- if .Values.secret.encryption.enabled }}
  encryptionPassphrase: {{ .Values.secret.encryption.passphrase }}
  {{- end }}
{{- end }}
