{{- if .Values.storageClass.enabled }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-ceph-rbd-sc-delete
  {{- if .Values.storageClass.delete.isDefault }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  {{- end }}
provisioner: rbd.csi.ceph.com
parameters:
  clusterID: {{ (index .Values.csiConfig 0).clusterID  }}
  pool: {{ .Values.storageClass.pool }}
  imageFeatures: layering
  csi.storage.k8s.io/provisioner-secret-name: {{ .Values.secret.name }}
  csi.storage.k8s.io/provisioner-secret-namespace: {{ .Release.Namespace }}
  csi.storage.k8s.io/controller-expand-secret-name: {{ .Values.secret.name }}
  csi.storage.k8s.io/controller-expand-secret-namespace: {{ .Release.Namespace }}
  csi.storage.k8s.io/node-stage-secret-name: {{ .Values.secret.name }}
  csi.storage.k8s.io/node-stage-secret-namespace: {{ .Release.Namespace }}
  csi.storage.k8s.io/fstype: {{ .Values.storageClass.delete.fstype }}
reclaimPolicy: Delete
allowVolumeExpansion: {{ .Values.storageClass.delete.allowVolumeExpansion }}
mountOptions:
  - discard
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-ceph-rbd-sc-retain
  {{- if .Values.storageClass.retain.isDefault }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  {{- end }}
provisioner: rbd.csi.ceph.com
parameters:
  clusterID: {{ (index .Values.csiConfig 0).clusterID }}
  pool: {{ .Values.storageClass.pool }}
  imageFeatures: layering
  csi.storage.k8s.io/provisioner-secret-name: {{ .Values.secret.name }}
  csi.storage.k8s.io/provisioner-secret-namespace: {{ .Release.Namespace }}
  csi.storage.k8s.io/controller-expand-secret-name: {{ .Values.secret.name }}
  csi.storage.k8s.io/controller-expand-secret-namespace: {{ .Release.Namespace }}
  csi.storage.k8s.io/node-stage-secret-name: {{ .Values.secret.name }}
  csi.storage.k8s.io/node-stage-secret-namespace: {{ .Release.Namespace }}
  csi.storage.k8s.io/fstype: {{ .Values.storageClass.retain.fstype }}
reclaimPolicy: Retain
allowVolumeExpansion: {{ .Values.storageClass.retain.allowVolumeExpansion }}
mountOptions:
  - discard
{{- end }}