{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.secret.namespace }}
stringData:
  userID: {{ .Values.secret.userID }}
  userKey: {{ .Values.secret.userKey }}
  adminID: {{ .Values.secret.adminID }}
  adminKey: {{ .Values.secret.adminKey }}
  {{- if .Values.secret.encryption.enabled }}
  encryptionPassphrase: {{ .Values.secret.encryption.passphrase }}
  {{- end }}
{{- end }}
