---
name: commitlint
# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - '*'
jobs:
  commitlint:
    name: commitlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: commitlint
        run: CONTAINER_CMD=docker make containerized-test TARGET=commitlint
