---
name: gosec
# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - '*'
jobs:
  gosec:
    name: gosec
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: gosec
        run: CONTAINER_CMD=docker make containerized-test TARGET=gosec
